services:
  argo-nezha-v1:
    image: ghcr.io/opengaoling/argo-nezha-v1:latest
    container_name: argo-nezha-v1
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./dashboard/data:/dashboard/data
      - ./dashboard/geoip:/dashboard/geoip
